In [1]:
import pandas as pd
import numpy as np
import re
import spacy

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
train_df = pd.read_pickle('/content/drive/MyDrive/FiNER_format/train_finer.pkl')
dev_df = pd.read_pickle('/content/drive/MyDrive/FiNER_format/dev_finer.pkl')
test_df = pd.read_pickle('/content/drive/MyDrive/FiNER_format/test_finer.pkl')
train_df.head()

,index,sentence,numerals-tags,company,docEndDate,docType,fileName,year,finer_masked_sentence,finer_num_sentence,finer_shape_sentence,ner_tags,tokens
0,6750,"On May 25, 2017, the district court awarded SR...",{'us-gaap:LossContingencyDamagesAwardedValue':...,"CISCO SYSTEMS, INC.","July 31, 2021",10-K,/home/soumyasharma/HULK/financial/FinNumRED/da...,21,"On May [MASK] , [MASK] , the district court aw...","On May [NUM] , [NUM] , the district court awar...","On May [XX] , [XXXX] , the district court awar...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[On, May, 25, ,, 2017, ,, the, district, court..."
1,60232,(a) - Balance includes $19.5 million of curren...,{'us-gaap:ContractWithCustomerLiabilityCurrent...,"ONEOK, Inc.","December 31, 2019",10-K,/home/soumyasharma/HULK/financial/FinNumRED/da...,20,( a ) - Balance includes $ [MASK] million of c...,( a ) - Balance includes $ [NUM] million of cu...,( a ) - Balance includes $ [XX.X] million of c...,"[0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0]","[(, a, ), -, Balance, includes, $, 19.5, milli..."
2,87151,The Company recorded a $30 benefit related to ...,{'us-gaap:IncomeTaxReconciliationChangeInEnact...,HOWMET AEROSPACE INC.,"December 31, 2020",10-K,/home/soumyasharma/HULK/financial/FinNumRED/da...,21,The Company recorded a $ [MASK] benefit relate...,The Company recorded a $ [NUM] benefit related...,The Company recorded a $ [XX] benefit related ...,"[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0]","[The, Company, recorded, a, $, 30, benefit, re..."
3,33525,The amount of ordinary dividends that may be p...,{'us-gaap:StatutoryAccountingPracticesStatutor...,HUMANA INC.,"December 31, 2019",10-K,/home/soumyasharma/HULK/financial/FinNumRED/da...,20,The amount of ordinary dividends that may be p...,The amount of ordinary dividends that may be p...,The amount of ordinary dividends that may be p...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[The, amount, of, ordinary, dividends, that, m..."
4,31645,(1)Corporate and Other includes gains of $428m...,{'us-gaap:DeconsolidationGainOrLossAmount': ['...,"Fiserv, Inc.","December 31, 2020",10-K,/home/soumyasharma/HULK/financial/FinNumRED/da...,21,( 1)Corporate and Other includes gains of $ 42...,( 1)Corporate and Other includes gains of $ 42...,( 1)Corporate and Other includes gains of $ 42...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[(, 1)Corporate, and, Other, includes, gains, ..."

In [8]:
regex = re.compile(r"(January|February|March|April|May|June|July|August|September|October|November|December)[ \t\n\r\f\v]*(3[0-2]|2[0-9]|1[0-9]|[1-9])(\,?)[ \t\n\r\f\v]*([12][0-9]\d\d)")  # date_masked_1
# regex = re.compile(r"((January|February|March|April|May|June|July|August|September|October|November|December)[ \t\n\r\f\v]*(3[0-2]|2[0-9]|1[0-9]|[1-9])(\,?)[ \t\n\r\f\v]*)?([12][0-9]\d\d)")  # date_masked_2

In [9]:
train_df['date_masked'] = train_df['sentence'].apply(lambda row : re.sub(regex, "[DATE]", row, count=0, flags=0))
train_df.to_pickle('/content/drive/MyDrive/FiNER_format/date_masked/train_finer.pkl')
dev_df['date_masked'] = dev_df['sentence'].apply(lambda row : re.sub(regex, "[DATE]", row, count=0, flags=0))
dev_df.to_pickle('/content/drive/MyDrive/FiNER_format/date_masked/dev_finer.pkl')
test_df['date_masked'] = test_df['sentence'].apply(lambda row : re.sub(regex, "[DATE]", row, count=0, flags=0))
test_df.to_pickle('/content/drive/MyDrive/FiNER_format/date_masked/test_finer.pkl')